# Generated by Django 6.0.4 on 2026-04-25 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('qoshimcha_ma_lumot', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muhtojlik_turi', models.CharField(choices=[('oziq_ovqat', '🍞 Oziq-ovqat'), ('dori', '💊 Dori-darmon'), ('ijara', '🏠 Ijara/uy'), ('toy', "💒 To'y yordami"), ('taziya', "🕌 Ta'ziya yordami"), ('talim', "📚 Ta'lim/maktab"), ('kasalxona', '🏥 Kasalxona/davolash'), ('boshqa', '📋 Boshqa')], max_length=30, verbose_name='Muhtojlik turi')),
                ('mazmun', models.TextField(verbose_name='Murojaat mazmuni')),
                ('priority', models.IntegerField(choices=[(1, '🔴 Favqulodda — Darhol yordam kerak'), (2, '🟠 Yuqori — Tezkor yordam kerak'), (3, "🟡 O'rta — Yaqin orada yordam kerak"), (4, '🟢 Past — Kechiktirilishi mumkin'), (5, "⚪ Minimal — Imkon bo'lsa yordam")], default=3, verbose_name='Muhimlik darajasi')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('korib_chiqilmoqda', "Ko'rib chiqilmoqda"), ('yordam_berildi', 'Yordam berildi'), ('rad_etildi', 'Rad etildi'), ('kechiktirildi', 'Kechiktirildi')], default='yangi', max_length=30, verbose_name='Holat')),
                ('murojaat_sanasi', models.DateField(verbose_name='Murojaat sanasi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('yordam_sanasi', models.DateField(blank=True, null=True, verbose_name='Yordam berilgan sana')),
                ('yordam_turi', models.CharField(blank=True, max_length=200, verbose_name='Yordam turi')),
                ('yordam_miqdori', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Yordam miqdori (so'm)")),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('mas_ul_hodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boshqargan_murojaatlar', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul hodim")),
                ('shaxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murojaatlar', to='murojaatlar.shaxs')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['priority', '-murojaat_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('imam', 'Bosh Imom'), ('hodim', 'Masjid Hodimi')], default='hodim', max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
