# Generated by Django 5.2.14 on 2026-05-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murojaatlar', '0004_modernize_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
    ]
