# Generated by Django 5.2.14 on 2026-05-17 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murojaatlar', '0005_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yordam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('pul', '💵 Pul'), ('oziq_ovqat', '🍞 Oziq-ovqat'), ('kiyim', '👕 Kiyim-kechak'), ('dori', '💊 Dori-darmon'), ('mahsulot', '📦 Mahsulot/jihoz'), ('xizmat', '🛠 Xizmat'), ('boshqa', '📋 Boshqa')], db_index=True, default='pul', max_length=20, verbose_name='Yordam turi')),
                ('miqdor', models.DecimalField(blank=True, decimal_places=0, help_text="Pul bo'lsa — summa. Mahsulot bo'lsa — taxminiy qiymat (ixtiyoriy).", max_digits=14, null=True, verbose_name="Miqdor (so'm)")),
                ('mazmun', models.TextField(blank=True, help_text="Masalan: '5 kg sahar, 2L yog''.", verbose_name='Tavsif')),
                ('bergan_fio', models.CharField(max_length=200, verbose_name='Yordam bergan shaxs')),
                ('bergan_telefon', models.CharField(blank=True, max_length=32, verbose_name='Telefon (ixtiyoriy)')),
                ('sana', models.DateField(db_index=True, verbose_name='Sana')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('murojaat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yordamlar', to='murojaatlar.murojaat', verbose_name="Bog'liq murojaat")),
                ('qabul_qilgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_qilgan_yordamlar', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan hodim')),
                ('shaxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yordamlar', to='murojaatlar.shaxs', verbose_name='Yordam beriluvchi')),
            ],
            options={
                'verbose_name': 'Yordam',
                'verbose_name_plural': 'Yordamlar',
                'ordering': ['-sana', '-yaratilgan'],
                'indexes': [models.Index(fields=['shaxs', '-sana'], name='yordam_shaxs_sana_idx'), models.Index(fields=['-sana'], name='yordam_sana_desc_idx')],
            },
        ),
    ]
